otel.service.name=unknown-service-name
otel.traces.exporter=otlp
otel.metrics.exporter=otlp
otel.logs.exporter=otlp
otel.exporter.otlp.protocol=grpc
otel.exporter.otlp.endpoint=http://otel-collector:4317
otel.metric.export.interval=5000

otel.traces.sampler=traceidratio
otel.traces.sampler.arg=0.05

otel.sdk.disabled=false